import "~/styles/globals.css";
import { Inter } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";
import Image from "next/image";
import discountImg from "public/images/DiscountBanner.png"
import headerImg from "public/images/TopHeader.png"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Creat e-commerce web App",
  description: "Generated by situn using create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
      <header>
        <Image src={headerImg} alt="headerImg" style={{width:"100%"}}/>
        <Image src={discountImg} alt="headerImg" style={{width:"100%"}} />

      </header>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
